### ISSUE TITLE
different build behaviors

### ISSUE THREAD

**Issue by stephenfournier** [stephenfournier/Dota-2-Building-Helper#14]
ex. wc3:

 Different behaviors:
                Human - Multiple Peasants can actively help in the construction, making it faster. If no peasants building, it stays at the same HP. Extra peasants use +gold/+lumber, counts as Repairing
                Orc - Single Peon, actively builds. Builder is hidden inside.
                NightElf - Wisp is hidden during the construction process. Ancient buildings will consume the unit.
                Undead - Building is queued and autobuilt without the Acolyte being there.
 
Buildings start at 10% HP.

**Comment by MNoya** [comment]
Added all of these in next update
