### ISSUE TITLE
Remove building not working correctly

### ISSUE THREAD

**Issue by XavierCHN** [stephenfournier/Dota-2-Building-Helper#29]
when building was killed/removed, square was not re-enabled correctly.
Scripts in line [buildinghelper.lua@735](https://github.com/Myll/Dota-2-Building-Helper/blob/master/game/dota_addons/samplerts/scripts/vscripts/buildinghelper.lua#L735) should be:
```Lua
BuildingHelper:OpenSquares(unit.squaresOccupied, "vector")
```

**Comment by MNoya** [comment]
New API will be `BuildingHelper:RemoveBuilding( building, bForcedKill )`
