### ISSUE TITLE
building ghost is laggy in multiplayer

### ISSUE THREAD

**Issue by stephenfournier** [stephenfournier/Dota-2-Building-Helper#39]
this is probably the most important issue in BH currently. the ghost will lag because the particles are not client-side (i.e. client needs to constantly talk to the server in order to display the ghost particles). 

the best solution would be to find a way to create client-side particles. 

a current solution that requires a lot of work is to display 64x64 movieclips to replace the square particles. this will have no regard for the terrain unfortunately.

**Comment by AeroHand** [comment]
how would u process the phantom model if u use movie clip?

**Comment by Myll** [comment]
don't know. wouldn't be able to

**Comment by snipplets** [comment]
I've done some limited testing (2 players on LAN) and setting [the delta](https://github.com/Myll/Dota-2-Building-Helper/blob/master/game/dota_addons/samplerts/scripts/vscripts/buildinghelper.lua#L324) to around 0.5 seems to be potentially viable workaround in the interim. Having it at 0.03 is really quite over the top I think. You don't need that much precision that fast.

If someone else is able to test it with more players or not over LAN I'd be interested to see how it goes.

But you're correct that client side completely is the dream.

**Comment by MNoya** [comment]
The dream is real :joy:
