### ISSUE TITLE
Square collision 

### ISSUE THREAD

**Issue by okokookokok** [stephenfournier/Dota-2-Building-Helper#44]
Sorry if this is the wrong place to ask a question. 

Is there a way to make a buildings' collision box square and be precisely the same as the building ghost? So far it seems I can only figure out how to make the collision "boxes" circles.

**Comment by Myll** [comment]
yep in dota 2 rectangular collision can only be achieved by changing the gridnav. To change unit collision you can only do SetHullRadius.

**Comment by okokookokok** [comment]
I see, too bad. Is there any good values if I'm trying to create a TD with mazing? My units seem able to slip between my buildings unless I place them on a straight line.

**Comment by MNoya** [comment]
You could try  creating point_simple_obstruction entities on top of your buildings or filling the whole build-able area with them and disable each one separately, drop your question over https://moddota.com/forums/categories/development and I'll elaborate it further

**Comment by Myll** [comment]
Placing an invisible dummy between two buildings should work.

**Comment by okokookokok** [comment]
Thanks a lot both of you. I created a question here: https://moddota.com/forums/discussion/208/square-collision-using-building-helper

**Comment by MNoya** [comment]
This issue actually spawned the current gridnav-block system :+1: 

Implemented in next.

**Comment by okokookokok** [comment]
Great to hear so!
Are you going to work on this buildinghelper instead of snipplets' panorama version? Or simply just merging them back together?

**Comment by MNoya** [comment]
I was using snipplets version with the  css grid system, but after Valve finally released clientside particles I went ahead and rewrote much of the lua to use in [DotaCraft](https://github.com/MNoya/DotaCraft) ( [buildinghelper lua history here](https://github.com/MNoya/DotaCraft/commits/master/game/dota_addons/dotacraft/scripts/vscripts/libraries/buildinghelper.lua), and added some extra features. It will be up today with a detailed Read Me and API wiki

**Comment by okokookokok** [comment]
That sounds great! 
Thanks for your hard work.
