### ISSUE TITLE
Created building does not properly assign owner.

### ISSUE THREAD

**Issue by Silent331** [stephenfournier/Dota-2-Building-Helper#49]
Issue: Owner is not received (returns nil) on the building when invoking :GetOwner() on the building.

Fix: Change the line that reads 

local building = CreateUnitByName(unitName, location, false, playersHero, nil, builder:GetTeam())

to

local building = CreateUnitByName(unitName, location, false, playersHero, builder:GetOwner(), builder:GetTeam())

<3 from the ID dev team

**Comment by MNoya** [comment]
Fixed in next
