### ISSUE TITLE
Tab building doesn't consume gold

### ISSUE THREAD

**Issue by nikitinalexx** [stephenfournier/Dota-2-Building-Helper#51]
Nuff said

**Comment by MNoya** [comment]
The Tab issue changed into this:
- Select 2 builders
- Start ghost with the first one
- Tab to the second
- Place the building
**Result**: Error, as the second builder was never initialized. Doesn't happen a second time for each builder.

Also, I'm not sure what the behavior should be when you select a builder + some other unit and tab to the non-builder unit while having a building ghost enabled. Right now the ghost remains and doesn't clear until you send a move order to them or just tab back to the builder and place it. Thoughts?
