### ISSUE TITLE
Blight api for setting up a level.

### ISSUE THREAD

**Issue by ynohtna92** [stephenfournier/Dota-2-Building-Helper#58]
Can we have a SetGridAsBlight API function in the building helper for setting up a level?

For example setting spawn as blight so buildings with a flag that restricts building on blight cannot be built.

**Comment by MNoya** [comment]
How this could be done:

- Have trigger zones on the map, all with the same particular name (in this case, "Blight").
- BuildingHelper:LoadGrid("Blight"), does FindAllByName of the passed string, checks its GetBounds and keeps a [x,y] for each WorldToGridPosX inside those triggers.
- This grid could be passed to all clients to have the grid particle update clientside
- 2 new building ability keys: 
  - `"Requires" "Blight"`, check if the squares are valid in the passed name grid and **only** let you build on top of those, mark as invalid if one or more squares don't meet the requirement.
  - `"Restricted" "Blight"`, check if the squares are valid and mark as invalid if one or more squares have the restriction

"Blight" it's just a string, this system could be used to define all sort of mechanics, most of #59, TD build zones, etc.

It would also require some new API functions, to modify each custom grid dynamically, such as:
- `BuildingHelper:ModifyGrid( name, location, size, bEnabled )` for squares
- `BuildingHelper:RemoveGrid( name, location, radius )` for AoE circle effects

A particle name with a spread parameter is also desirable.

**Comment by ynohtna92** [comment]
You could have the key split with spaces so it would look like 
`"Requires" "Buildable Blight"`

It may be annoying to have requires buildable on every building though.

**Comment by MNoya** [comment]
Buildable is just the natural gridnav. If you wanted to prevent that, it would take the Restricted key.

**Comment by MNoya** [comment]
Ok I finally got it, this will be the new update of the KV system:

* `"ConstructionSize" "8"` - Global buildable grid, a square of 8 size valid positions has to be found for a building to be valid. The gridnav pathing isn't blocked with this.
* `"BlockGridNavSize"`"6"` - In addition to blocking 8 squares, the gridnav pathing can be blocked independently with this. It won't be really used to determine a valid position anymore.
* `"Requires" "Buildable"` - The default key, and will be taken by omission unless specified so.
* `"Requires" "SomeString"` - This will only look for grid marked under the 'SomeString' grid, and ignores the Buildable grid. Example: "GoldMine"
* `"Requires" "Buildable Blight"` - Separated by spaces as suggested
* `"Prevent" "SomeOtherString"` - Apart from meeting the Requires criteria, perform an additional check on this other grid. Example: "Path"

**Comment by ynohtna92** [comment]
Will construction size block future buildings from being built there even if the block gridnav is smaller?

**Comment by MNoya** [comment]
BlockGridNav only affects pathing. ConstructionSize sets Buildable = false

**Comment by TideSofDarK** [comment]
Why space separation?
Maybe
 "Requires" "BH_BUILDABLE | BH_BLIGHT"
?

**Comment by MNoya** [comment]
Caps would indicate predefined constants, apart from *Buildable*, the rest are user-defined.
**|** indicates "or", the Requires key would check for all the required condition, so something like `"Requires" "Buildable Blight Water Poison"` reads natural I think

**Comment by ynohtna92** [comment]
This should be helpful. http://www.hiveworkshop.com/forums/general-mapping-tutorials-278/pathing-everything-about-154558/#p2

**Comment by MNoya** [comment]
This confirms my suspicion damn
![img](http://666kb.com/i/bfgjsrmhes8wwe9dv.gif)

**Comment by MNoya** [comment]
Done in https://github.com/MNoya/BuildingHelper/commit/bfa858bc7339f841cf73e0bc1578b28afd901c23
