### ISSUE TITLE
Building ghosts left hanging

### ISSUE THREAD

**Issue by okokookokok** [stephenfournier/Dota-2-Building-Helper#60]
If you set a builder to build a building which consumes the builder but at the same time shiftsqueue multiple buildings, then the building ghosts are left hanging, and it seems there is no way to get rid of them once the first building is complete. 

While building it is possible to right click anywhere to remove the ghosts.

https://imgur.com/3ENico2

**Comment by MNoya** [comment]
I forgot to add a ClearQueue in the OnEntityKilled event when I was removing code for the fork. Should be fixed now
