### ISSUE TITLE
Upgrade Building API

### ISSUE THREAD

**Issue by ynohtna92** [stephenfournier/Dota-2-Building-Helper#66]
For WC3 emulation, when upgrading a building the steps are as follows:
- Create new building with no abilities & no vision (the old building will be hidden :AddNoDraw()? ) and a upgrade cancel button/item.
- The building will grow/construct over time until the build duration is completed.
- When construction is completed the old building will be removed from the game and the new building will be granted its vision and abilities.

**Comment by MNoya** [comment]
With the building queue system, do you really want no abilities? Hiding abilities can be done very easily through the builder.lua callbacks if you so desire, it's just iterating OnConstructionStarted, `SetHidden(false)` and OnConstructionCompleted do the opposite.

For grow, there is the Scale key (which isn't used on the examples but it's still there)

**Comment by ynohtna92** [comment]
Thats how wc3 is I believe, I'm trying to get the mechanics exact for my game mode. But I guess unlearned abilities will work as well.
