### ISSUE TITLE
The building ghost model will only display correctly on the first run in the Workshop Tools

### ISSUE THREAD

**Issue by stephenfournier** [stephenfournier/Dota-2-Building-Helper#7]
You need to restart the workshop tools to see the full building ghost model again. It will only display correctly on the first run. On further runs, it only shows the base model without cosmetics.

**Comment by MNoya** [comment]
Are you sure about this? While testing I restarted a couple of times and it still showed up.

However, I'm not getting the grid, just the model:

![img](http://imgur.com/CbaZrJt)

**Comment by Myll** [comment]
currently the model size is independent of the grid size. in the future i should scale the model before creating the particle so that the model fits inside the grid.

**Comment by MNoya** [comment]
Yeah I understand the issue now, the ghost particle is indeed missing the cosmetics if you spawn a npc_dota_hero or even a npc_dota_unit. Model shows fine at the end, so it's a pretty minor problem

![img](http://puu.sh/fXd2h/40b1dee3a3.jpg)

We should test these particles in 2nd-3rd player clients next
