### ISSUE TITLE
Issuing orders "inside" buildings

### ISSUE THREAD

**Issue by KirmesBude** [stephenfournier/Dota-2-Building-Helper#70]
**Summary:**
Builders can do stuff while constructing a building from the "inside"
Most notably repair - speeds up the time to reach full hp on the building

**Repro Steps:**

1. Build a City Center
2. Select your builder and repair your City Center

**Result:**

Building reaches full health and you have to wait forever

**Expected Result:**

You probably should not be able to issue any order to the builder "inside"

**Comment by MNoya** [comment]
Builders should still be to add orders to their queue while inside (I deliberately allowed this behavior). The problem would being able to repair the building on the first place, as the **"BuilderInside" behavior is not supposed to be used with Require Repair**. This BuilderInside key already reserves the builder during the whole construction process, and unless you want your Assist-Repair to also additional builders inside (which would need some additional changes), buildings should never be repair-able while building something with that behavior. This can be changed in the builder.lua, checking the target and interrupting whenever you don't want to allow the same action

For reference, BuilderInside behavior is mimicking the Orc & Night Elf building behaviors of Warcraft 3.

**Comment by KirmesBude** [comment]
> Builders should still be able to add orders to their queue while inside (I deliberately allowed this behavior).
> For reference, BuilderInside behavior is mimicking the Orc & Night Elf building behaviors of Warcraft 3.

True, that makes sense - did not think about that. I always forget this is at the core groundwork for warcraft/dotacraft/rts /:P



> The problem would be being able to repair the building on the first place, as the "BuilderInside" behavior is not supposed to be used with Require Repair.
> This BuilderInside key already reserves the builder during the whole construction process, and unless you want your Assist-Repair to also additional builders inside (which would need some additional changes), buildings should never be repair-able while building something with that behavior. This can be changed in the builder.lua, checking the target and interrupting whenever you don't want to allow the same action

That is not whats happening here though, is it?
City Center does not have the Requires Repair Key set.

Either manually repairing from the inside should actually speed up construction or you should not be able to repair from the inside at all.

**Comment by MNoya** [comment]
It seems I forgot to add a restriction in builder.lua to never repair something from inside. It should certainly not speed up the construction, in theory the builder is already "repairing it from inside". Will be fixed in the next update
